#ifndef START_DEFINE_REG
#define START_DEFINE_REG
#endif

#ifndef END_DEFINE_REG
#define END_DEFINE_REG
#endif

#ifndef START_DEFINE_CONSTANT
#define START_DEFINE_CONSTANT
#endif

#ifndef END_DEFINE_CONSTANT
#define END_DEFINE_CONSTANT
#endif

#ifndef DEFINE_REG
#define DEFINE_REG(R,V)
#endif

#ifndef DEFINE_CONSTANT
#define DEFINE_CONSTANT(R,V)
#endif

START_DEFINE_CONSTANT
#ifdef CONFIG_ARCH_FPU
DEFINE_CONSTANT(SW_FPU_REGS,33)
#else
DEFINE_CONSTANT(SW_FPU_REGS,0)
#endif

#ifdef CONFIG_BUILD_PROTECTED
DEFINE_CONSTANT(SW_INT_REGS,11)
#else
DEFINE_CONSTANT(SW_INT_REGS,10)
#endif

DEFINE_CONSTANT(SW_XCPT_REGS,SW_INT_REGS + SW_FPU_REGS)
DEFINE_CONSTANT(SW_XCPT_SIZE,4 * SW_XCPT_REGS)
DEFINE_CONSTANT(HW_XCPT_REGS,8)
DEFINE_CONSTANT(HW_XCPT_SIZE,4 * HW_XCPT_REGS)

DEFINE_CONSTANT(XCPTCONTEXT_REGS,HW_XCPT_REGS + SW_XCPT_REGS)
DEFINE_CONSTANT(XCPTCONTEXT_SIZE,HW_XCPT_SIZE + SW_XCPT_SIZE)
END_DEFINE_CONSTANT

START_DEFINE_REG
DEFINE_REG(R13,0)  /* R13 = SP at time of interrupt */
#ifdef CONFIG_ARMV7M_USEBASEPRI
DEFINE_REG(BASEPRI,1)  /* BASEPRI */
#else
DEFINE_REG(PRIMASK,1)  /* PRIMASK */
#endif
DEFINE_REG(R4,2)  /* R4 */
DEFINE_REG(R5,3)  /* R5 */
DEFINE_REG(R6,4)  /* R6 */
DEFINE_REG(R7,5)  /* R7 */
DEFINE_REG(R8,6)  /* R8 */
DEFINE_REG(R9,7)  /* R9 */
DEFINE_REG(R10,8)  /* R10 */
DEFINE_REG(R11,9)  /* R11 */

#ifdef CONFIG_BUILD_PROTECTED
DEFINE_REG(EXC_RETURN,10) /* EXC_RETURN */
#endif

#if defined(START_DEFINE_FPU) || defined(DEFINE_FPD_REG) || defined(DEFINE_FPS_REG)
#include "reg_fp_macro.h"
#endif

/* The total number of registers saved by software */



/* On entry into an IRQ, the hardware automatically saves the following
 * registers on the stack in this (address) order:
 */

DEFINE_REG(R0,SW_XCPT_REGS+0) /* R0 */
DEFINE_REG(R1,SW_XCPT_REGS+1) /* R1 */
DEFINE_REG(R2,SW_XCPT_REGS+2) /* R2 */
DEFINE_REG(R3,SW_XCPT_REGS+3) /* R3 */
DEFINE_REG(R12,SW_XCPT_REGS+4) /* R12 */
DEFINE_REG(R14,SW_XCPT_REGS+5) /* R14 = LR */
DEFINE_REG(R15,SW_XCPT_REGS+6) /* R15 = PC */
DEFINE_REG(XPSR,SW_XCPT_REGS+7) /* xPSR */
END_DEFINE_REG


#undef START_DEFINE_REG
#undef END_DEFINE_REG
#undef START_DEFINE_CONSTANT
#undef END_DEFINE_CONSTANT
#undef DEFINE_REG
#undef DEFINE_CONSTANT

#undef START_DEFINE_DFPU
#undef END_DEFINE_DFPU
#undef START_DEFINE_SFPU
#undef END_DEFINE_SFPU
